version: '3'

services:
  test:
    build:
      context: .
      dockerfile: ./compose/Dockerfile_test
    command:
      bash -c "python -m pytest --cov-config=../coveragerc.ini --cov=. -vv && flake8"

